# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceb9fed8ad4162bcc5693b3dab0e0b2bdf56e866d3681fb7527bb1f9f36b49ca2017c2b0253f3a8eb592fb71b791463589aa5fbaecdd84f15897553c2b5b3d74

test:
  secret_key_base: c6d254dd0ad8b463218290199eca648bd42e244a09a1ae5a2245ea318dfd07d5e64423cf4db8ecff20827df5f0028ccb86f6d330ab635403c5cf60a236732f9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
